### ISSUE TITLE
patch to build with auto* build system

### ISSUE THREAD

**Issue by arekm** [giddie/poppler-cairo-backend#2]
Tiny patch that gets patchset usable with old build system:
http://ixion.pld-linux.org/~arekm/poppler-qt4-cairo-backend-fixes.patch

**Comment by giddie** [comment]
Hmm; I'm not sure that it's correct to link poppler-qt4 against poppler-glib.  The correct solution would be to build the CairoOutputDev into poppler-qt4, as in the CMake build configuration.

**Comment by arekm** [comment]
Makes sense.
