### ISSUE TITLE
Fails to build on debian

### ISSUE THREAD

**Issue by AladW** [giddie/poppler-cairo-backend#4]
Hi,

When applying the patches to the debian package (poppler 0.24-5), the build fails with the following error:

../../poppler/CairoOutputDev.h:38:22: fatal error: cairo-ft.h: No such file or directory
 #include <cairo-ft.h>
                     ^
compilation terminated.

However, the necessary header is available
`libcairo2-dev: /usr/include/cairo/cairo-ft.h`

I've found this:

http://www.seppemagiels.com/blog/building-poppler-windows-using-mingw

so the file is mislocated? Where could I change the reference?

Regards,

Alad

**Comment by giddie** [comment]
I'm not sure if the Debian package is doing something strange. Could you try compiling Poppler directly from source, with the patch applied?

**Comment by AladW** [comment]
Well the original source gave the same error message. So what I did was create symbolic links

/usr/include/cairo
`for a in * ; do ln -s /usr/include/cairo/$a /usr/include/$a ; done`

/usr/include/freetype2
`for a in * ; do ln -s /usr/include/freetype2/$a /usr/include/$a ; done`

but hit another wall

```
Making all in tests
make[3]: Map '/home/alad/source/poppler-qt4-cairo-backend/qt4/tests' wordt binnengegaan
  CXX      test-poppler-qt4.o
  CXXLD    test-poppler-qt4
../../qt4/src/.libs/libpoppler-qt4.so: undefined reference to `CairoOutputDev::startDoc(PDFDoc*, CairoFontEngine*)'
../../qt4/src/.libs/libpoppler-qt4.so: undefined reference to `cairo_image_surface_create_for_data'
../../qt4/src/.libs/libpoppler-qt4.so: undefined reference to `cairo_surface_destroy'
../../qt4/src/.libs/libpoppler-qt4.so: undefined reference to `cairo_create'
../../qt4/src/.libs/libpoppler-qt4.so: undefined reference to `CairoOutputDev::CairoOutputDev()'
../../qt4/src/.libs/libpoppler-qt4.so: undefined reference to `cairo_destroy'
../../qt4/src/.libs/libpoppler-qt4.so: undefined reference to `CairoOutputDev::setCairo(_cairo*)'
collect2: error: ld returned 1 exit status
```

**Comment by giddie** [comment]
When you say the "original source", do you mean unpatched Poppler? Or does this only happen with my patches applied?

**Comment by AladW** [comment]
With the patches applied (qt4-lcd branch)

**Comment by giddie** [comment]
Are you building with autotools? If you're are, I'm afraid I'm not maintaining that in the patchset, as autotools is a real pain. You'll have to build with cmake, as described in the patchset readme. (Patches are welcome to fix the autotools build!)
